swagger: "2.0"
info:
  version: 1.0.0
  title: "api-nauts"
  description: API to get informations on astronauts in space
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: trentose2jan12-nauts.herokuapp.com
basePath: /nauts
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: |
        Find informations about an astronaut
      operationId: getNauts
      parameters:
        - name: lastName
          in: query
          description: Astronaut to search
          required: false
          type: string
      responses:
        200:
          description: List of astronauts with the given last name
          schema:
            type: array
            items:
              $ref: '#/definitions/Astronauts'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: |
        Add a new astronaut
      operationId: addNauts
      parameters:
        - name: astronauts
          in: body
          description: New astronaut to add
          required: true
          schema:
            $ref: '#/definitions/NewAstronaut'
      responses:
        201:
          description: New astronaut created
          schema:
            $ref: '#/definitions/Astronauts'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /nauts/{lastName}:
    get:
      description: Returns astronaut with given id
      operationId: findnautsby lastName
      parameters:
        - name: lastName
          in: path
          description: id of astronaut with given last name
          required: true
          type: string
          x-example: 'some-example'
      responses:
        200:
          description: OK - astronaut
          schema:
            $ref: '#/definitions/Astronauts'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

    put:
      description: Updates an existing astronaut, or create a new one with lastName.
      operationId: update astronauts
      parameters:
        - name: lastName
          in: path
          description: ID of assignment to edit or create
          required: true
          type: string
          x-example: 'some-example'
        - name: assignment
          in: body
          description: assignment
          required: true
          schema:
            $ref: '#/definitions/Astronauts'
      responses:
        202:
          description: assignment update response
          schema:
            $ref: '#/definitions/Astronauts'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Astronauts:
    allOf:
      - $ref: '#/definitions/NewAstronaut'
      - required:
        - nautid
        properties:
          nautid:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          isInSpace: 
            type: boolean
  NewAstronaut:
    required:
      - nautid
      - firstName
      - lastName
      - isInSpace
    properties:
      nautid:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      isInSpace:
        type: boolean
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string